export const Models = Object.freeze({
  USER: 'user',
  TEAM: 'team',
  MATCH: 'match',
  SCORE: 'score',
  STAGE: 'stage',
  COUNTRY: 'country',
  STANDINGS: 'standings',
  TOURNAMENT: 'tournament',
  PREDICTION: 'prediction',
  MATCH_SCORE: 'matchScore',
  MODERATOR: 'moderator',
  FEATURE: 'feature',
  AUTHORITY: 'authority',
});
