BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Match] ALTER COLUMN [homeTeamId] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Match] ALTER COLUMN [awayTeamId] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Match] ALTER COLUMN [stageId] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
